### ISSUE TITLE
Standardize annotations to be excluded from integration test scope

### ISSUE THREAD

**Issue by jhorstmann** [whiskeysierra/archer#12]
Normally our integration tests exclude Gateways and replace them with mocks. But what about model / domain classes used by the gateways?

**Comment by whiskeysierra** [comment]
Can't we used `@Gateway` as an exclusion filter? Only the gateway (and related mappers/helpers) will be managed e.g. by Spring. Model/Domain classes are free to be used (still annotated with `@Gateway` since they belong to the layer, conceptually).
